[package]
name = "cnbackend"
version = "0.1.0"
edition = "2021"

[dependencies]
cncommon = { path = "../cncommon" }
# external dependencies
anyhow = "1.0.83"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
futures = "0.3.30"
